package/optee-benchmark: fix gcc 10 warning
The function yaml_mapping_start_event_initialize()
take yaml_mapping_style_t style as last argument:

int yaml_mapping_start_event_initialize(
    yaml_event_t *event,
    const yaml_char_t *anchor,
    const yaml_char_t *tag,
    int implicit,
    yaml_mapping_style_t style)

Use YAML_ANY_MAPPING_STYLE instead of YAML_ANY_SEQUENCE_STYLE

Fixes:
main.c:173:5: error: implicit conversion from ‘enum yaml_sequence_style_e’ to ‘yaml_mapping_style_t’ {aka ‘enum yaml_mapping_style_e’} [-Werror=enum-conversion]
  173 |     YAML_ANY_SEQUENCE_STYLE))
      |     ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Cc: Etienne Carriere <etienne.carriere@linaro.org>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>