configs/ci20: use upstream Linux and U-Boot
The vendor kernel we are currently selecting no longer builds,
and fails with a ton of:

                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from arch/mips/jz4740/prom.c:16:
include/linux/log2.h:22:1: error: ignoring attribute 'noreturn' because it conflicts with attribute 'const' [-Werror=a
ttributes]
   22 | int ____ilog2_NaN(void);
      | ^~~

We can't afford to fix that, so let's just move to upstream
kernel and bootloader. It doesn't make much sense to keep
using an unsupported kernel and bootloader at this point.

This means we will be missing some of the features supported
by the vendor (such as HDMI support), but it is what it is.

Linux v5.7 and v5.4 have been tested to boot fine, the latter
is picked for the defconfig as it is an LTS version.

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/674933782

Reported-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Ezequiel Garcia <ezequiel@collabora.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>